### PR TITLE
Refactor of SubscriptionsStore.matches

### PR DESCRIPTION
**Pull request by AndreasMager**
Motivation:
LinkedBlockingDeque is a bad choice in this use case. It is designed for concurrent scenarios.
This implementaition is single threaded.

I have measured some implementations  the winner was a array of Token.

### CODE REVIEW

**Comment by andsel** [comment]
Could you share such measurements?
Deque was used because the work on stacked tokens, so the abstract data type of Deque must be maintained, we could change the implementation, for example if arrays is more performant, we can use ArrayDeque

**Comment by AndreasMager** [comment]
Ok @andsel if have tested the ArrayDeque and its the fastes of all even with all the copy operations.
If it's stupid but it works it ain't stupid.

ArrayDeque vs []
deque wins with 95% less time

[] vs LinkedBlockingDeque
[] wins with 89% less time

ArrayList and LinkedList are slightly slower than [].

**Comment by andsel** [comment]
Before to decide if a thing is good or bad I would like to see the test code, so that I can reproduce it on my laptop, or at least the description of the testbed plus the results in terms of number of insertion/deletion per seconds.

**Comment by AndreasMager** [comment]
The test code is pref/../SubscriptionStoreTest. I have  change the code to test both implementation in the same test run.

**Comment by AndreasMager** [comment]
Hi @andsel . I have added a temporary commit with both implementations.

Minimum time of 500 Testruns:
new implementation took 225ms
old implementation took 263ms

**Comment by AndreasMager** [comment]
The code became removed.

**Pull request closed without merging**
