### PR TITLE
MemorySessionStore: Session class added

### PR DESCRIPTION
**Pull request by AndreasMager**
A new class added for easier session cleanup and LRU Cache etc.

### CODE REVIEW

**Comment by andsel** [comment]
Hi @AndreasMager  could you explain/comment a little bit about this PR?

**Comment by AndreasMager** [comment]
The whole data structure of the a session is broken splitted over several Map in Maps because of the old MapDB implementation. The MemoryStorage implementation doesn't need this burden.

The Session cleanup should be done by the Storage implementation. Your new commit goes in this way with dropInFlightMessagesInSession Method. 

The MemoryStorage needs a method to cleanup old outdated session like a LRU Cache to avoid OutOfMemoryExceptions. 

I want to implement the guava CacheBuilder for this task.

**Comment by andsel** [comment]
The PR seems good to me, I agree with you. Once you squash all the commits I merge it. Thanks

**Comment by AndreasMager** [comment]
Fixes #325

**Comment by AndreasMager** [comment]
@andsel rebased and squashed

**Pull request merged**
