### PR TITLE
fix(refactor): fixed typo IntegrationUtils.prepareTestProperties()

### PR DESCRIPTION
**Pull request by mackristof**

### CODE REVIEW

**Comment by mackristof** [comment]
build fail on ServerIntegrationSSLClientAuthTest. checkClientAuthentification() cause 
ssl certificate for "signedtestclient" expired on  Tue May 17 10:55:02 CEST 2016  :(

**Comment by andsel** [comment]
Hi @mackristof the title of the PR is a little different from what it implements. Could you describe better how you integrated Hazelcast and why, HA it's an important brick in the broker so before accepting such PR, problably it's better to describe it a little bit. 
Thanks Andrea

**Comment by mackristof** [comment]
Sorry, it's m'y bad. Hazelcast integration still in WIP.

**Comment by mackristof** [comment]
But you can, if you want, take a look on my fork 😉

**Comment by andsel** [comment]
Sometime ago I've done some thoughts about this, I come up with an idea of how to use Hazelcast to make Moquette HA, if you want we can share in pwt or mailing list

 Andrea

**Comment by mackristof** [comment]
No problem. What do you mean by "pwt" ??

**Comment by andsel** [comment]
I open a thread on the mailing lists

**Pull request closed without merging**
