### PR TITLE
OSGify broker

### PR DESCRIPTION
**Pull request by gg-dim**
## Release notes

Generate correct MANIFEST.MF with bnd 

## What does this PR do?

We added the ```bnd-maven-plugin``` to the parent pom.xml and a ```bnd.bnd``` file to generate a correct and complete ```MANIFEST.MF``` needed for OSGi and other projects to use the broker.

## Why is it important/What is the impact to the user?

Without a correct MANIFEST.MF the broken can't be used in several open source (OSGi based) projects.

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files (and/or docker env variables)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] I have updated the Changelog if it's a feature or a fix that has to be reported

## Author's Checklist

- [ ]

## How to test this PR locally

Add the Broker to a OSGi or BND project.

## Related issues

-

### CODE REVIEW

**Comment by andsel** [comment]
Thank's @gg-dim for contributing. 
Is the BND plugin executed during the usual flow of generation of Moquette jars? 
Did you tested on an OSGi container?

**Comment by gg-dim** [comment]
Yes, the BND part is done while generation of the jars. 
Yes, I tested it in an OSGi environment. We use a locally build variant in our [org.gecko.messaging](https://github.com/geckoprojects-org/org.gecko.messaging) project. I built an OSGi service around it, which is used in our n-n tests as a MQTT broker (e.g. [Test](https://github.com/geckoprojects-org/org.gecko.messaging/blob/main/org.gecko.adapter.mqtt.v5.tests/src/org/gecko/adapter/mqtt/tests/MqttComponentReconnectTest.java))

**Review by andsel — APPROVED** [review]
LGTM

**Comment by andsel** [comment]
Thanks @gg-dim for contributing! Once CI finish, I'll merge it.

**Pull request merged**
