### PR TITLE
use moquette path property where possible

### PR DESCRIPTION
**Pull request by maggu2810**
We should always prefer the moquette.path system property before we fill
the home directory of the user with files.

The formatter removes some trailing whitespaces.

### CODE REVIEW

**Comment by maggu2810** [comment]
Sure, this would be possible, but not in scope of that PR.
This PR should just respect mosquitto.path for the storage similar to the config, so the current bundle implementation works with it.

**Comment by maggu2810** [comment]
I think we (you?) should create an additional PR, so that all configuration values are part of the config properties. The location of the database should be a configuration parameter.
The static field is currently used by tests etc. So we could use that as a fallback if no configuration is set. In that case (configuration property is not set manually) I would prefer to keep this commits, so we could set mosquitto.path also for the test run and the user home directory is not filled with the storage files.

**Comment by andsel** [comment]
I think that the configuration (except for logging) should be kept in one place. Is PR's scope to permit the user to customize the data path? If it's yes, in my opinion I think it should be in moquette.conf, what to you think?

**Comment by maggu2810** [comment]
Yes, the intention was to change the data path.
Using moquette.conf (and so on the config properties) seems to be good.

But I think we should also change the default behavior if no configuration is available.
Running tests should never fill my user home directory, they should use a in-memory database (possibl using mapdb) or create a temporary directory to store all that stuff.

I used mosquitto.path in this PR because it was the simplest change.
But if I think about your comments, a config property would be the best (with a fallback to a "usefull" default behaviour, that keep my system clean).

Are there any requirements to keep a full backward compatibility? So, should we check if there is an existing database in user.home and move them to the "new" location?

**Comment by swarwick** [comment]
I changed my version of the code to allow for

m_properties.put("persistent_store", System.getProperty("user.home") + File.separator + "moquette_store.mapdb");

In the ConfigurationParser.java file (and of course other changes where needed for this change).  This allows me to specify the db store path and if its not specified it defaults to what it was before.  I am not able to commit this change for review but if you want me to just send a diff or something for you guys to add let me know.

**Comment by andsel** [comment]
I've merged the changes that @swarwick  created on his fork. Now the config file could use also "persistent_store" to define the path.

**Comment by maggu2810** [comment]
Could not read the sources ATM.
Your OSGi bundle is using the startServer() method.
So, what is the default location for the database, is there still the home directory used or are some properties preferred that I could set starting my OSGi container?
What is the location of the database the unit test are using?

**Comment by andsel** [comment]
In unit tests it has to be fixed, probably I'll set to string empty to force a memory DB (NB the MapDBPersistentStore default to memory if can't find the storage path).
For OSGi I've to fix completely the OSGi part due to bad visibility of classes that has to be used by MapDB, so the OSGi part for version 0.7 SNAPSHOT is to consider under development

**Comment by maggu2810** [comment]
Thank you for your feedback.

**Pull request closed without merging**
