### PR TITLE
Adding assertj to test dependencies

### PR DESCRIPTION
**Pull request by AndreasMager**
Assertj is a great library for writing junit test.

### CODE REVIEW

**Comment by andsel** [comment]
AssertJ seems promising, but has few stars on GitHub. Probably Hamcrest matchers or probably I would introduce Spckframework or JUnit 5 which should be GA for Q1 of 2017 (practically tomorrow). What do you think?

**Comment by AndreasMager** [comment]
I work for 2 years with assertj now. The collection methods and error checks in java 1.8 are nice. I'll take a look on your Suggestions. My preferred test library's are awaitility, mokito and assertj.

**Comment by AndreasMager** [comment]
JUnit 5 is java 1.8.
I thing Hamcrest matcher can be use in assertj. They are not so nice to use, because you must know the methods autocompletion struggles with this. 
Spockframework locks like python :D not my favorite
https://github.com/google/truth looks a bit like assertj.

**Comment by andsel** [comment]
I would move to Java 8 for release 0.10, surely version 1.0 is using Java
8, JUnit5 could be a good step  forward.

**Comment by andsel** [comment]
Really Spock is Groovy ;-)  You convinced me, I'll give a try to AssertJ, if the project in future is abandoned (that's my unique trouble about it) we can switch to Google's Truth or fallback on Hamcrest. JUnit 5 at the end to use fluent assert API suggest to use Hamcrest, Truth or AssertJ

**Pull request merged**
