### PR TITLE
Test setup improvement

### PR DESCRIPTION
**Pull request by AndreasMager**
ServerIntegrationSSLClientAuthTest and ServerLowlevelMessagesIntegrationTests change the System.properties this has side effects for following test. It makes some test runs flaky.

ServerLowlevelMessagesIntegrationTests: the test result is flacky on different system performances.

Osgi: The old test implementation ignored errors and the state of osgi packages

This pr is need for #345

### CODE REVIEW

**Comment by AndreasMager** [comment]
@andsel  there is a problem with the bugsnag + osgi

The Osgi tests fails:
org.osgi.framework.BundleException: Unable to resolve io.moquette.broker [16](R 16.0): missing requirement [io.moquette.broker [16](R 16.0)] osgi.wiring.package; (osgi.wiring.package=com.bugsnag) Unresolved requirements: [[io.moquette.broker [16](R 16.0)] osgi.wiring.package; (osgi.wiring.package=com.bugsnag)]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4090)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2111)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1365)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:748)

**Comment by AndreasMager** [comment]
The Pax-Exam caching is really weird. I can not remove bugsnag form build for testing. And it uses remote repositories for the test.
```
[INFO] Downloading: https://oss.sonatype.org/content/repositories/snapshots/io/moquette/moquette-broker/0.11-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: https://repo.eclipse.org/content/repositories/paho-releases/io/moquette/moquette-broker/0.11-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: https://oss.sonatype.org/content/repositories/snapshots/io/moquette/moquette-parent/0.11-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: https://repo.eclipse.org/content/repositories/paho-releases/io/moquette/moquette-parent/0.11-SNAPSHOT/maven-metadata.xml
[INFO] Downloading: https://repo.maven.apache.org/maven2/com/bugsnag/bugsnag/maven-metadata.xml
[INFO] Downloading: https://repo.eclipse.org/content/repositories/paho-releases/com/bugsnag/bugsnag/maven-metadata.xml
[INFO] Downloading: https://oss.sonatype.org/content/repositories/snapshots/com/bugsnag/bugsnag/maven-metadata.xml
[INFO] Downloaded: https://repo.maven.apache.org/maven2/com/bugsnag/bugsnag/maven-metadata.xml (976 B at 16.7 KB/sec)
[INFO] Downloaded: https://oss.sonatype.org/content/repositories/snapshots/com/bugsnag/bugsnag/maven-metadata.xml (397 B at 0.9 KB/sec)
[INFO] 

```

**Comment by AndreasMager** [comment]
@andsel Should i sqaush the commits again?

**Comment by AndreasMager** [comment]
@andsel PR is squashed and ready for review/merge

**Comment by andsel** [comment]
@AndreasMager  only one question, why including librato deps in broker/pom.xml while previously I used the dropwizard metrics's librato output ?

**Comment by AndreasMager** [comment]
@andsel com.librato.metrics:librato-java comes transitive in the broker:

```
+--- com.librato.metrics:metrics-librato:5.1.0
|    +--- com.librato.metrics:librato-java:2.1.0
|    |    +--- com.fasterxml.jackson.core:jackson-core:2.8.8
|    |    +--- com.fasterxml.jackson.core:jackson-databind:2.8.8
|    |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.8.0 -> 2.8.8
|    |    |    \--- com.fasterxml.jackson.core:jackson-core:2.8.8
|    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.8.8
```

The weird osgi meta file generator generates a bad file when its not a top level dependencie. Then the osgi test won't start the broker because of a dep error. I'am a osgi noob there might be other better solutions. I have no test system expect for the osgi test.
The previous osgi test didn't detect these dependencies errors.

The current master build log:

```
ERROR: Bundle io.moquette.broker [16] Error starting mvn:io.moquette/moquette-broker (org.osgi.framework.BundleException: Unable to resolve io.moquette.broker [16](R 16.0): missing requirement [io.moquette.broker [16](R 16.0)] osgi.wiring.package; (osgi.wiring.package=com.bugsnag) Unresolved requirements: [[io.moquette.broker [16](R 16.0)] osgi.wiring.package; (osgi.wiring.package=com.bugsnag)])
org.osgi.framework.BundleException: Unable to resolve io.moquette.broker [16](R 16.0): missing requirement [io.moquette.broker [16](R 16.0)] osgi.wiring.package; (osgi.wiring.package=com.bugsnag) Unresolved requirements: [[io.moquette.broker [16](R 16.0)] osgi.wiring.package; (osgi.wiring.package=com.bugsnag)]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4090)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2111)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1365)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.lang.Thread.run(Thread.java:748)

....

org.ops4j.pax.exam.invoker.junit 32
io.moquette.broker 2
```

io.moquette.broker 2 means loaded but not startet 32 would correct

**Comment by andsel** [comment]
:-( I hate OSGi, it's a great thing, but you always find yourself swamped in the mess of jars not designed as modules.

**Pull request merged**
