### PR TITLE
Upgrade netty to 4.1.22

### PR DESCRIPTION
**Pull request by sbouchex**
Upgraded netty to 4.1.22

### CODE REVIEW

**Comment by andsel** [comment]
Thanks for the PR @sbouchex 
 Andrea

**Comment by sbouchex** [comment]
@andsel Any plan to release a new version with this upgrade ?

**Comment by andsel** [comment]
At the moment no, I've other fixes to do, and I want to group them all
together.
 Andrea

**Comment by mscheibler** [comment]
Really nice!
I found out yesterday, that my PR depends on this one, as the old Netty version had an issue with native library loading. So your timing was perfect. :)

**Pull request merged**
