### PR TITLE
Chnages in Constants

### PR DESCRIPTION
**Pull request by shary998**
I have changed BROKER Constants file it now takes msg size dynamically

### CODE REVIEW

**Comment by hylkevds** [comment]
Changing a sensible _default_ value to an overly large value is not good. If you want to allow larger messages you can set the option `netty.mqtt.message_size`.

**Comment by shary998** [comment]
I ma doing Something Like this to connect this server only with matched credentials. But when I did this it always sets the msgs to its default size and I'll not be able to do my work. Kindly guide.

   val brokerProperties = PreferenceManager.getDefaultSharedPreferences(this)
         val pass =
             brokerProperties.getString("password", "password")
         val host =
             brokerProperties.getString("host", "192.168.5.10")
         val maxSize = brokerProperties.getString("netty.mqtt.message_size", "999999999")
         val wakeLock = brokerProperties.getString("wakelockduration", "2")

         val props = Properties()
         props.setProperty(
             BrokerConstants.PORT_PROPERTY_NAME,
             brokerProperties?.getString("port", "61613")
         )
         props.setProperty(BrokerConstants.NEED_CLIENT_AUTH, "ture")
         val username = brokerProperties.getString("username", "admin")
         val password = brokerProperties.getString("password", pass)

         if (password != null) {
             val sha256hex: String = DigestUtils.sha256Hex(password)
             val filename = "password.conf"
             val fileContents = "$username:$sha256hex"
             try {
                 openFileOutput(filename, MODE_PRIVATE).use { fos ->
                     fos.write(fileContents.toByteArray())
                     val file = File(filesDir, filename)
                     props.setProperty(
                         BrokerConstants.PASSWORD_FILE_PROPERTY_NAME,
                         file.absolutePath
                     )
                 }
             } catch (e: IOException) {
                 e.printStackTrace()
             }
         } else {
             Toast.makeText(this, "Unable to generate auth file", Toast.LENGTH_SHORT).show()
         }

         props.setProperty(BrokerConstants.HOST_PROPERTY_NAME, host)
         props.setProperty(
             BrokerConstants.WEB_SOCKET_PORT_PROPERTY_NAME,
             BrokerConstants.WEBSOCKET_PORT.toString()
         )

        val a = BrokerConstants.NETTY_MAX_BYTES_PROPERTY_NAME.toString()
         props.setProperty(a,maxSize)
         props.setProperty(BROKER_PROPERTY_WAKE_LOCK_DURATION, wakeLock)

        Intent(applicationContext, BrokerService::class.java).also {
            it.action = Action.START.name
            it.putExtra(CONST_JSONSTRINGDATA, gson.toJson(brokerProperties).toString())

**Comment by shary998** [comment]
> Changing a sensible _default_ value to an overly large value is not good. If you want to allow larger messages you can set the option `netty.mqtt.message_size`.


   val brokerProperties = PreferenceManager.getDefaultSharedPreferences(this)
         val pass =
             brokerProperties.getString("password", "password")
         val host =
             brokerProperties.getString("host", "192.168.5.10")
         val maxSize = brokerProperties.getString("netty.mqtt.message_size", "999999999")
         val wakeLock = brokerProperties.getString("wakelockduration", "2")

         val props = Properties()
         props.setProperty(
             BrokerConstants.PORT_PROPERTY_NAME,
             brokerProperties?.getString("port", "61613")
         )
         props.setProperty(BrokerConstants.NEED_CLIENT_AUTH, "ture")
         val username = brokerProperties.getString("username", "admin")
         val password = brokerProperties.getString("password", pass)

         if (password != null) {
             val sha256hex: String = DigestUtils.sha256Hex(password)
             val filename = "password.conf"
             val fileContents = "$username:$sha256hex"
             try {
                 openFileOutput(filename, MODE_PRIVATE).use { fos ->
                     fos.write(fileContents.toByteArray())
                     val file = File(filesDir, filename)
                     props.setProperty(
                         BrokerConstants.PASSWORD_FILE_PROPERTY_NAME,
                         file.absolutePath
                     )
                 }
             } catch (e: IOException) {
                 e.printStackTrace()
             }
         } else {
             Toast.makeText(this, "Unable to generate auth file", Toast.LENGTH_SHORT).show()
         }

         props.setProperty(BrokerConstants.HOST_PROPERTY_NAME, host)
         props.setProperty(
             BrokerConstants.WEB_SOCKET_PORT_PROPERTY_NAME,
             BrokerConstants.WEBSOCKET_PORT.toString()
         )

        val a = BrokerConstants.NETTY_MAX_BYTES_PROPERTY_NAME.toString()
         props.setProperty(a,maxSize)
         props.setProperty(BROKER_PROPERTY_WAKE_LOCK_DURATION, wakeLock)

        Intent(applicationContext, BrokerService::class.java).also {
            it.action = Action.START.name
            it.putExtra(CONST_JSONSTRINGDATA, gson.toJson(brokerProperties).toString())

**Comment by hylkevds** [comment]
Where are you sending those properties to Moquette?

**Pull request closed without merging**
